config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root :to => 'inicio#index'
  get 'inicio/index'
  resources :cliente_recepcions

  resources :recepcions

  resources :clientes

  resources :mascota

  resources :servicios

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :cliente_recepcion
  has_many :recepcion, :through => :cliente_recepcion
  belongs_to :mascota
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellido, :correo, :direccion, :mascota_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :mascota_id %><br>
    <%= f.select( "mascota_id",Mascotum.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Elija su Mascota'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Crear Cliente</h1>

<%= render 'form' %>

<%= link_to 'Motrar', @cliente %> |
<%= link_to 'Regresar', clientes_path %>

app/views/clientes/index.html.erb
<h1>Clientes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th class="info">Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Direccion</th>
      <th>Mascota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.correo %></td>
        <td><%= cliente.direccion %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Regresar', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @cliente.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @cliente.correo %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Mascota:</strong>
  <%= @cliente.mascotum.nombre %>
</p>



<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Regresar', clientes_path %>