config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root :to => 'inicio#index'
  get 'inicio/index'
  resources :cliente_recepcions

  resources :recepcions

  resources :clientes

  resources :mascota

  resources :servicios

end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  before_action :set_servicio, only: [:show, :edit, :update, :destroy]

  # GET /servicios
  # GET /servicios.json
  def index
    @servicios = Servicio.all
  end

  # GET /servicios/1
  # GET /servicios/1.json
  def show
  end

  # GET /servicios/new
  def new
    @servicio = Servicio.new
  end

  # GET /servicios/1/edit
  def edit
  end

  # POST /servicios
  # POST /servicios.json
  def create
    @servicio = Servicio.new(servicio_params)

    respond_to do |format|
      if @servicio.save
        format.html { redirect_to @servicio, notice: 'Servicio was successfully created.' }
        format.json { render :show, status: :created, location: @servicio }
      else
        format.html { render :new }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicios/1
  # PATCH/PUT /servicios/1.json
  def update
    respond_to do |format|
      if @servicio.update(servicio_params)
        format.html { redirect_to @servicio, notice: 'Servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @servicio }
      else
        format.html { render :edit }
        format.json { render json: @servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicios/1
  # DELETE /servicios/1.json
  def destroy
    @servicio.destroy
    respond_to do |format|
      format.html { redirect_to servicios_url, notice: 'Servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servicio
      @servicio = Servicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servicio_params
      params.require(:servicio).permit(:tratamiento, :valor, :cita, :producto)
    end
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/servicios/_form.html.erb
<%= form_for(@servicio) do |f| %>
  <% if @servicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servicio.errors.count, "error") %> prohibited this servicio from being saved:</h2>

      <ul>
      <% @servicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tratamiento %><br>
    <%= f.text_field :tratamiento %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :cita %><br>
    <%= f.date_select :cita %>
  </div>
  <div class="field">
    <%= f.label :producto %><br>
    <%= f.text_field :producto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicios/edit.html.erb
<h1>Nuevo Servicio</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @servicio %> |
<%= link_to 'Regresar', servicios_path %>

app/views/servicios/index.html.erb
<h1>Servicios</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Tratamiento</th>
      <th>Valor</th>
      <th>Cita</th>
      <th>Producto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicios.each do |servicio| %>
      <tr>
        <td><%= servicio.tratamiento %></td>
        <td><%= servicio.valor %></td>
        <td><%= servicio.cita %></td>
        <td><%= servicio.producto %></td>
        <td><%= link_to 'Mostrar', servicio %></td>
        <td><%= link_to 'Editar', edit_servicio_path(servicio) %></td>
        <td><%= link_to 'Eliminar', servicio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Servicio', new_servicio_path %>

app/views/servicios/new.html.erb
<h1>Nuevo Servicio</h1>

<%= render 'form' %>

<%= link_to 'Regresar', servicios_path %>

app/views/servicios/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Tratamiento:</strong>
  <%= @servicio.tratamiento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @servicio.valor %>
</p>

<p>
  <strong>Cita:</strong>
  <%= @servicio.cita %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @servicio.producto %>
</p>

<%= link_to 'Editar', edit_servicio_path(@servicio) %> |
<%= link_to 'Regresar', servicios_path %>