config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root :to => 'inicio#index'
  get 'inicio/index'
  resources :cliente_recepcions

  resources :recepcions

  resources :clientes

  resources :mascota

  resources :servicios

end

app/models/recepcion.rb
class Recepcion < ActiveRecord::Base
  has_many :cliente_recepcion
  has_many :cliente, :through => :cliente_recepcion
end

app/controllers/recepcions_controller.rb
class RecepcionsController < ApplicationController
  before_action :set_recepcion, only: [:show, :edit, :update, :destroy]

  # GET /recepcions
  # GET /recepcions.json
  def index
    @recepcions = Recepcion.all
  end

  # GET /recepcions/1
  # GET /recepcions/1.json
  def show
  end

  # GET /recepcions/new
  def new
    @recepcion = Recepcion.new
  end

  # GET /recepcions/1/edit
  def edit
  end

  # POST /recepcions
  # POST /recepcions.json
  def create
    @recepcion = Recepcion.new(recepcion_params)

    respond_to do |format|
      if @recepcion.save
        format.html { redirect_to @recepcion, notice: 'Recepcion was successfully created.' }
        format.json { render :show, status: :created, location: @recepcion }
      else
        format.html { render :new }
        format.json { render json: @recepcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recepcions/1
  # PATCH/PUT /recepcions/1.json
  def update
    respond_to do |format|
      if @recepcion.update(recepcion_params)
        format.html { redirect_to @recepcion, notice: 'Recepcion was successfully updated.' }
        format.json { render :show, status: :ok, location: @recepcion }
      else
        format.html { render :edit }
        format.json { render json: @recepcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recepcions/1
  # DELETE /recepcions/1.json
  def destroy
    @recepcion.destroy
    respond_to do |format|
      format.html { redirect_to recepcions_url, notice: 'Recepcion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recepcion
      @recepcion = Recepcion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recepcion_params
      params.require(:recepcion).permit(:nombre, :apellido, :cargo, :telefono)
    end
end

app/helpers/recepcions_helper.rb
module RecepcionsHelper
end

app/views/recepcions/_form.html.erb
<%= form_for(@recepcion) do |f| %>
  <% if @recepcion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recepcion.errors.count, "error") %> prohibited this recepcion from being saved:</h2>

      <ul>
      <% @recepcion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recepcions/edit.html.erb
<h1>Nueva Recepcion</h1>

<%= render 'form' %>

<%= link_to 'Show', @recepcion %> |
<%= link_to 'Back', recepcions_path %>

app/views/recepcions/index.html.erb
<h1>Recepcion</h1>

<table class="table table-bordered">
    <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Cargo</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recepcions.each do |recepcion| %>
      <tr>
        <td><%= recepcion.nombre %></td>
        <td><%= recepcion.apellido %></td>
        <td><%= recepcion.cargo %></td>
        <td><%= recepcion.telefono %></td>
        <td><%= link_to 'Mostrar', recepcion %></td>
        <td><%= link_to 'Editar', edit_recepcion_path(recepcion) %></td>
        <td><%= link_to 'Eliminar', recepcion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Recepcion', new_recepcion_path %>

app/views/recepcions/new.html.erb
<h1>New recepcion</h1>

<%= render 'form' %>

<%= link_to 'Regresar', recepcions_path %>

app/views/recepcions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @recepcion.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @recepcion.apellido %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @recepcion.cargo %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @recepcion.telefono %>
</p>

<%= link_to 'Editar', edit_recepcion_path(@recepcion) %> |
<%= link_to 'Regresar', recepcions_path %>