config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  root :to => 'inicio#index'
  get 'inicio/index'
  resources :cliente_recepcions

  resources :recepcions

  resources :clientes

  resources :mascota

  resources :servicios

end

app/models/cliente_recepcion.rb
class ClienteRecepcion < ActiveRecord::Base
  belongs_to :cliente
  belongs_to :recepcion
end

app/controllers/cliente_recepcions_controller.rb
class ClienteRecepcionsController < ApplicationController
  before_action :set_cliente_recepcion, only: [:show, :edit, :update, :destroy]

  # GET /cliente_recepcions
  # GET /cliente_recepcions.json
  def index
    @cliente_recepcions = ClienteRecepcion.all
  end

  # GET /cliente_recepcions/1
  # GET /cliente_recepcions/1.json
  def show
  end

  # GET /cliente_recepcions/new
  def new
    @cliente_recepcion = ClienteRecepcion.new
  end

  # GET /cliente_recepcions/1/edit
  def edit
  end

  # POST /cliente_recepcions
  # POST /cliente_recepcions.json
  def create
    @cliente_recepcion = ClienteRecepcion.new(cliente_recepcion_params)

    respond_to do |format|
      if @cliente_recepcion.save
        format.html { redirect_to @cliente_recepcion, notice: 'Cliente recepcion was successfully created.' }
        format.json { render :show, status: :created, location: @cliente_recepcion }
      else
        format.html { render :new }
        format.json { render json: @cliente_recepcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cliente_recepcions/1
  # PATCH/PUT /cliente_recepcions/1.json
  def update
    respond_to do |format|
      if @cliente_recepcion.update(cliente_recepcion_params)
        format.html { redirect_to @cliente_recepcion, notice: 'Cliente recepcion was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente_recepcion }
      else
        format.html { render :edit }
        format.json { render json: @cliente_recepcion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliente_recepcions/1
  # DELETE /cliente_recepcions/1.json
  def destroy
    @cliente_recepcion.destroy
    respond_to do |format|
      format.html { redirect_to cliente_recepcions_url, notice: 'Cliente recepcion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente_recepcion
      @cliente_recepcion = ClienteRecepcion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_recepcion_params
      params.require(:cliente_recepcion).permit(:cliente_id, :recepcion_id)
    end
end

app/helpers/cliente_recepcions_helper.rb
module ClienteRecepcionsHelper
end

app/views/cliente_recepcions/_form.html.erb
<%= form_for(@cliente_recepcion) do |f| %>
  <% if @cliente_recepcion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente_recepcion.errors.count, "error") %> prohibited this cliente_recepcion from being saved:</h2>

      <ul>
      <% @cliente_recepcion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br>
      <%= f.select( "cliente_id",Cliente.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Elija Cliente'}) %>
  </div>
  <div class="field">
    <%= f.label :recepcion_id %><br>
      <%= f.select( "recepcion_id",Recepcion.all.collect{|l| [ l.nombre, l.id ] }, {include_blank: 'Elija Recepcion'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cliente_recepcions/edit.html.erb
<h1>Recepcion Cliente</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cliente_recepcion %> |
<%= link_to 'Regresar', cliente_recepcions_path %>

app/views/cliente_recepcions/index.html.erb
<h1>Clientes Recepciones</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Recepcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cliente_recepcions.each do |cliente_recepcion| %>
      <tr>
        <td><%= cliente_recepcion.cliente.nombre%></td>
        <td><%= cliente_recepcion.recepcion.nombre %></td>
        <td><%= link_to 'Mostrar', cliente_recepcion %></td>
        <td><%= link_to 'Editar', edit_cliente_recepcion_path(cliente_recepcion) %></td>
        <td><%= link_to 'Eliminar', cliente_recepcion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Recepciones', new_cliente_recepcion_path %>

app/views/cliente_recepcions/new.html.erb
<h1>Nueva Recepciones</h1>

<%= render 'form' %>

<%= link_to 'Volver', cliente_recepcions_path %>

app/views/cliente_recepcions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Cliente:</strong>
  <%= @cliente_recepcion.cliente.nombre %>
</p>

<p>
  <strong>Recepcion:</strong>
  <%= @cliente_recepcion.recepcion.nombre %>
</p>

<%= link_to 'Editar', edit_cliente_recepcion_path(@cliente_recepcion) %> |
<%= link_to 'Volver', cliente_recepcions_path %>